//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAnalytics.Models {
	using System;
	using System.Collections.Generic;
	using MibClient2.Objects;
	
	public partial class AdmUser : MibObject {
		public AdmUser(int id) : 
				base(id, "ADM_USERS") {
		}
		public AdmUser() : 
				base("ADM_USERS") {
		}
		public virtual System.DateTime Dateins {
			get {
				return this.GetDateTime("DATEINS");
			}
			set {
				this.SetField("DATEINS", value);
			}
		}
		public virtual int Owner {
			get {
				return this.GetInt32("OWNER");
			}
			set {
				this.SetField("OWNER", value);
			}
		}
		public virtual bool Enabled {
			get {
				return this.GetBoolean("ENABLED");
			}
			set {
				this.SetField("ENABLED", value);
			}
		}
		public virtual string Login {
			get {
				return this.GetString("LOGIN");
			}
			set {
				this.SetField("LOGIN", value);
			}
		}
		public virtual string Password {
			get {
				return this.GetString("PASSWORD");
			}
			set {
				this.SetField("PASSWORD", value);
			}
		}
		public virtual string Company {
			get {
				return this.GetString("COMPANY");
			}
			set {
				this.SetField("COMPANY", value);
			}
		}
		public virtual string Email {
			get {
				return this.GetString("EMAIL");
			}
			set {
				this.SetField("EMAIL", value);
			}
		}
		public virtual string InitialAddin {
			get {
				return this.GetString("INITIAL_ADDIN");
			}
			set {
				this.SetField("INITIAL_ADDIN", value);
			}
		}
	}
}
namespace DXAnalytics.Models {
	using System;
	using System.Collections.Generic;
	using MibClient2.Objects;
	
	public partial class SubscriptionPlan : MibObject {
		public SubscriptionPlan(int id) : 
				base(id, "DX_SUBSCRIPTION_PLANS") {
		}
		public SubscriptionPlan() : 
				base("DX_SUBSCRIPTION_PLANS") {
		}
		public virtual System.DateTime Dateins {
			get {
				return this.GetDateTime("DATEINS");
			}
			set {
				this.SetField("DATEINS", value);
			}
		}
		public virtual int SkinId {
			get {
				return this.GetInt32("SKIN_ID");
			}
			set {
				this.SetField("SKIN_ID", value);
			}
		}
		public virtual string PlanOptions {
			get {
				return this.GetString("PLAN_OPTIONS");
			}
			set {
				this.SetField("PLAN_OPTIONS", value);
			}
		}
	}
}
